## Aufgabe: Neuronales Netz

Diese Programieraufgabe berechnet ein neuronales Netz für einen Beispieldatensatz. Es geht darum einen Klassifizierer zu trainieren, der Ziffern erkennen soll.

Gegeben sind folgende Ziffern zum Training:


![](numbers.jpg)

### Augabe 1:

Bilden sie die Ziffern in einem Numpy-Array X ab und und die Label in einem weiteren Numpy-Array Y:

In [2]:
import numpy as np
np.set_printoptions(suppress=True)

In [ ]:
X = np.array([[0,0,1,0,0.... ],  # Ziffer '1'
              [0,1,1,0,1 .... ],  # Ziffer '2'
              [0,1,1,0, ...  ]]) # Ziffer '3'

Y = np.array([[1,0,0],  # klassifiziert als ‚1’
              [...],  # klassifiziert als ‚2’
              [...]]) # klassifiziert als ‚3’

## Aufgabe 2:


Schreiben Sie die Hilfsfunktionen zur Berechnung des sigmoid und der Funktion eines Neuron (incl. Aktivierung durch sigmoids):

In [7]:
# Sigmoid Berechnung
def sigmoid(x):
    # your code goes here
    return ...

# Ableitung vom sigmoid
def sigmoid_d(x):
    return sigmoid(x)*(1-sigmoid(x))

# Neuron 
def neuron(I,W,f):
    # your code goes here
    return ...

def layer(I,W):
    # your code goes here
    return ...

# Test
print(layer(np.array([1,2,3]), np.array([1,1,1]), sigmoid))

# das Resultat sollte 0.9975273768433653 sein!!!!


0.9975273768433653


### Aufgabe 3:

Initialisiere das neuronale Netz und verknüpfe die Layer. Das Netz sollte einen Input-Layer (L0), 1 Hidden-Layer (L1) und einen Output-Layer (L3) haben.



In [26]:
# Initialisierung
np.random.seed(1)       

# Verknuepfe Input- mit Hidden-Layer

# wieviele  Eingangswerte gibt es?
# und waehle beliebig Neuronen im Hidden-Layer
W0 = np.random.random((??,??)) 

# Verknuepfe Hidden- mit Output-Layer

# wieviele  Ausgangswerte gibt es?

W1 = np.random.random((??,??))


L0 = X              # Input Layer
L1 = neuron(L0, W0)  # Hidden Layer
L3 = neuron(L1, W1)  # Output Layer
print(L3)

# Das sollte laufen und folgendes ausgeben
#[[0.99999987 0.99999897 0.99999929]
# [0.99999992 0.99999932 0.9999995 ]
# [0.99999992 0.99999931 0.9999995 ]]


[[0.99999987 0.99999897 0.99999929]
 [0.99999992 0.99999932 0.9999995 ]
 [0.99999992 0.99999931 0.9999995 ]]


## Aufgabe 4:

Das eigentliche Herzstück: Implementiere den Backpropagation-Algorithmus über dieses neuronale Netz. Hierzu:
1. Berechne das Resultat, sprich führe Forward-Propagation aus
2. Ermittle den Fehler zwischen dem Resultat und Y
3. Bestimme das Delta mit dem die Wichtungen zwischen Hidden und Output-Layer angepasst werden muss
4. Bestimme das Delta mit dem die Wichtungen zwischen Hidden und Input-Layer anpasst werden muss
5. Wiederhole das Ganze, bis der Fehler kleiner 0.05 ist!

In [27]:
for i in range(60000):
    # forward processing
    L0 = 
    L1 = 
    L3 = 
    
    
    # bestimme den Fehler und berechne Delta und anpassung auf Hidden-Layer
    L3_err = 
    L3_delta = 
    W1 += 
    
    print("%s Error: %6.10f" % (i,np.mean(np.abs(L3_err))))
        
    # bestimme den Fehler und berechne Delta und anpassung auf Input-Layer
    L1_err =     
    L1_delta = 
    W0 += 
    

0 Error: 0.6666664684
1 Error: 0.6532297798
2 Error: 0.3335503084
3 Error: 0.4857498090
4 Error: 0.3684471186
5 Error: 0.6226404010
6 Error: 0.3334557970
7 Error: 0.4484668228
8 Error: 0.4027772739
9 Error: 0.5400987772
10 Error: 0.3447847136
11 Error: 0.5710967506
12 Error: 0.3582730959
13 Error: 0.4691820316
14 Error: 0.4098541233
15 Error: 0.4590375682
16 Error: 0.4429856326
17 Error: 0.5147953030
18 Error: 0.3566456630
19 Error: 0.4735943397
20 Error: 0.3602927298
21 Error: 0.5524502545
22 Error: 0.3335885476
23 Error: 0.5313577609
24 Error: 0.3620581886
25 Error: 0.4276051789
26 Error: 0.3539517666
27 Error: 0.5168308066
28 Error: 0.4263797779
29 Error: 0.3881121379
30 Error: 0.3420964238
31 Error: 0.4377456062
32 Error: 0.3048748720
33 Error: 0.4488094186
34 Error: 0.3306011919
35 Error: 0.5153013873
36 Error: 0.3330783323
37 Error: 0.3727043320
38 Error: 0.2961838752
39 Error: 0.4968660455
40 Error: 0.3309216504
41 Error: 0.3720174572
42 Error: 0.3233973557
43 Error: 0.500760012

### Aufgabe 5:
Zeit zum Testen. Wir schauen mal ob das Modell nun auch Abweichungen erkennen kann und richtig klassifiziert.
Hierzu gibt es folgende Abweichungen:

![Abweichungen](numbers_new.jpg)

Zunächst kurz überlegen, wie das als Numpy-Array abgebildet werden kann!

In [21]:
# Test 1
L0 = np.array([...])
L1 = layer(L0, W0)
L3 = layer(L1, W1)

print(L2)

# Ausgabe etwas wie
# [[0.95764431 0.02022213 0.00282105]]


[[0.95764431 0.02022213 0.00282105]]


Was heisst das Ergebnis?

Test 2

In [22]:
# Test 2
L0 = np.array([...])
L1 = layer(L0, W0)
L3 = layer(L1, W1)

print(L2)

# Ausgabe etwas wie
# [[0.88233092 0.05561936 0.00533852]]

[[0.88233092 0.05561936 0.00533852]]
