In [2]:
import tensorflow as tf

2022-04-05 08:42:57.667893: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-05 08:42:57.667929: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [5]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)


tf.Tensor(4, shape=(), dtype=int32)


In [6]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [7]:
# If you want to be specific, you can set the dtype
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [9]:
a = tf.add(3, 5)
print(a.numpy())

8


In TensorFlow 2, eager execution is turned on by default.

You can use tf.function to make graphs out of your programs. It is a transformation tool that creates Python-independent dataflow graphs out of your Python code. This will help you create performant and portable models, and it is required to use SavedModel.

The main takeaways and recommendations are:

- Debug in eager mode, then decorate with @tf.function.
- Don't rely on Python side effects like object mutation or list appends.
- tf.function works best with TensorFlow ops; NumPy and Python calls are converted to constants.


In [16]:
def add(a, b):
  return a + b

r = add(tf.ones([2, 2]), tf.ones([2, 2]))  #  [[2., 2.], [2., 2.]]

print(r)


tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)


In [24]:
@tf.function
def dense_layer(x, w, b):
  return add(tf.matmul(x, w), b)

dense_layer(tf.ones([3, 2]), tf.ones([2, 2]), tf.ones([2]))


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.],
       [3., 3.]], dtype=float32)>

In [25]:
import random as rn

@tf.function
def train(dataset):
  loss = tf.constant(0)
  for x, y in dataset:
    loss += tf.abs(y - x) # Some dummy computation.
  return loss

small_data = [(rn.randint(0,3), rn.randint(2,5))] * 3
big_data = [(rn.randint(0,3), rn.randint(2,5))] * 10

print(train(small_data))
print(train(big_data))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
